### PR TITLE
Create easyTable.v03.js

### PR DESCRIPTION
**Pull request by fearlessforever**

### CODE REVIEW

**Comment by gabriel-rodrigues-42** [comment]
Hi, 

Thank you for improve this plugin, before merge the branch, could you do some changes?

1° Use camelCase Identation, example: `button_desc as buttonDesc or buttonIcon, make_menu as makeMenu`  it's just a pattern that I want to follow for all my plugins :+1: .

2º Add option to replace the text of Search in `<label class="input-group-addon"> Search </label>`

**Comment by fearlessforever** [comment]
done . there you go .

anyway in my pc , i have added some fitur again , just simple pagination button , when its clicked it will change the page number but if callback was set , it will call the function .
should i pull new request or just commit change again ?

**Comment by gabriel-rodrigues-42** [comment]
Commit change again.

**Comment by fearlessforever** [comment]
there you go

**Pull request merged**
